[project]
name = "prova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "googletrans>=4.0.2",
    "jupyter>=1.1.1",
    "selenium>=4.38.0",
    "tqdm>=4.67.1",
]
